# Generated by Django 5.2.13 on 2026-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_group', models.CharField(choices=[('all', 'All'), ('subscribers', 'Subscribers Only'), ('customers', 'Customers Only'), ('dealers', 'Active Dealers Only'), ('custom', 'Custom Selection')], max_length=20)),
                ('sent_to_emails', models.JSONField(default=list, help_text='List of emails this was sent to')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'newsletters',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
