# Generated by Django 5.2.14 on 2026-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_newsletter_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='welcomed_at',
            field=models.DateTimeField(blank=True, help_text='Set when the welcome email succeeds.', null=True),
        ),
    ]
