# Generated by Django 5.2.13 on 2026-05-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_erp_sync_status_order_updated_at_order_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="gst_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Full price at time of order (before discount)",
                max_digits=10,
            ),
        ),
    ]
