# Generated by Django 5.2.14 on 2026-05-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_cancellation_reason_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dealer_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='razorpay', help_text='razorpay / cod / credit (dealer-only) / wallet (dealer-only).', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, help_text='Purchase order number (dealer).', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='preferred_carrier',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
