# Generated by Django 5.2.14 on 2026-05-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_backorder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_company_name',
            field=models.CharField(blank=True, help_text='Company name snapshotted at order time (dealers only).', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_gstin',
            field=models.CharField(blank=True, help_text='GSTIN snapshotted at order time. Empty for B2C.', max_length=15),
        ),
    ]
