# Generated by Django 5.2.14 on 2026-06-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_refund_gateway_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_card_code',
            field=models.CharField(blank=True, db_index=True, max_length=19),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
