# Generated by Django 5.2.13 on 2026-04-24 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("wood", "Wood"),
                            ("metal", "Metal"),
                            ("fabric", "Fabric"),
                            ("leather", "Leather"),
                            ("glass", "Glass"),
                            ("plastic", "Plastic"),
                            ("marble", "Marble"),
                            ("rattan", "Rattan"),
                        ],
                        max_length=50,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                (
                    "dimensions",
                    models.CharField(help_text="e.g., 120x60x75 cm", max_length=100),
                ),
                (
                    "image_url",
                    models.URLField(
                        help_text="External URL for the product image", max_length=500
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
    ]
