# Generated by Django 5.2.13 on 2026-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_add_is_featured_updated_at_description_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_categor_4083ff_idx",
            old_name="products_ca_id_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_materia_a1405d_idx",
            old_name="products_ma_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="products_price_fe467e_idx",
            old_name="products_pr_idx",
        ),
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(max_length=500),
        ),
    ]
