# Generated by Django 5.2.13 on 2026-05-06 11:02

from django.db import migrations


def backfill_media(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductMedia = apps.get_model('products', 'ProductMedia')
    for product in Product.objects.exclude(image_url=''):
        if product.image_url and not ProductMedia.objects.filter(product=product).exists():
            ProductMedia.objects.create(
                product=product,
                kind='image',
                file=product.image_url,
                is_primary=True,
                order=0,
                alt_text=product.name,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_productmedia"),
    ]

    operations = [
        migrations.RunPython(backfill_media, migrations.RunPython.noop),
    ]
