# Generated by Django 5.2.14, hand-edited to backfill SKUs before applying
# the unique constraint on Product.sku.
import secrets

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


def backfill_product_skus(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    used = set(
        Product.objects.exclude(sku__isnull=True).exclude(sku='').values_list('sku', flat=True)
    )
    for product in Product.objects.filter(models.Q(sku__isnull=True) | models.Q(sku='')).iterator():
        base = (product.category.slug[:3].upper() if product.category_id else 'PRD')
        for _ in range(20):
            candidate = f'{base}-{secrets.token_hex(3).upper()}'
            if candidate not in used:
                used.add(candidate)
                product.sku = candidate
                product.save(update_fields=['sku'])
                break


def noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_backfill_product_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Weight, Warranty', max_length=100)),
                ('value', models.CharField(help_text='e.g. 12 kg, 2 years', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'product_specifications',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, db_index=True, max_length=40, unique=True)),
                ('option_name', models.CharField(help_text='e.g. Color, Size', max_length=50)),
                ('option_value', models.CharField(help_text='e.g. Walnut, Large', max_length=50)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_variants',
                'ordering': ['option_name', 'option_value'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='banner'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='products.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        # SKU: add nullable first, backfill, then enforce unique.
        # NOTE: no db_index here — the later unique=True alter already creates
        # the index (incl. Postgres' varchar_pattern_ops `_like` index). Having
        # db_index=True here too made Postgres try to create that `_like` index
        # twice ("relation products_sku_..._like already exists"). SQLite/MySQL
        # tolerated it; Postgres (Neon) does not.
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(backfill_product_skus, reverse_code=noop),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', max_length=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'option_name', 'option_value')},
        ),
    ]
