# Generated by Django 5.2.14 on 2026-05-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_brand_product_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealer_only',
            field=models.BooleanField(db_index=True, default=False, help_text='Hide from public storefront; only visible to authenticated dealers.'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity per order (MOQ). Enforced at add-to-cart and checkout.'),
        ),
    ]
