# Generated by Django 5.2.14 on 2026-05-13 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(db_index=True, default=False)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_stock_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='deliveryrule',
            new_name='product_del_product_ffea0f_idx',
            old_name='product_dr_product_min_qty_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='product_tag_is_navi_8d25ac_idx',
            old_name='product_tags_nav_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='product_tag_categor_50cfc0_idx',
            old_name='product_tags_cat_nav_idx',
        ),
        migrations.AlterField(
            model_name='deliveryrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Set when a signed-in user subscribed; null for guests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stockalert',
            index=models.Index(fields=['product', 'notified'], name='product_sto_product_a1cea4_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockalert',
            constraint=models.UniqueConstraint(condition=models.Q(('notified', False)), fields=('product', 'email'), name='uniq_open_stock_alert_per_email'),
        ),
    ]
