# Generated by Django 5.2.14 on 2026-05-10 05:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('pincode_prefix', models.CharField(db_index=True, help_text='Leading digits of pincode. Longer = more specific.', max_length=6)),
                ('base_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('per_kg_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Additional fee per kilogram (charged on items > 1 kg).', max_digits=8)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cart subtotal at/above which shipping is free for this zone. 0 = always charge.', max_digits=10)),
                ('etd_days_min', models.PositiveSmallIntegerField(default=3)),
                ('etd_days_max', models.PositiveSmallIntegerField(default=7)),
                ('cod_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipping_zones',
                'ordering': ['-pincode_prefix'],
            },
        ),
    ]
