# Generated by Django 5.2.14 on 2026-05-09 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0002_invoice_amount_due_invoice_amount_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('terms_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dealer_credit',
            },
        ),
        migrations.CreateModel(
            name='DealerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('cash', 'Cash'), ('razorpay', 'Razorpay')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='UTR / cheque # / transaction ID.', max_length=80)),
                ('note', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, help_text='Optional — NULL means an on-account / advance payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_payments', to='invoices.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_dealer_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dealer_payments',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['dealer', '-received_at'], name='dealer_paym_dealer__990590_idx')],
            },
        ),
    ]
