# Generated by Django 5.2.14 on 2026-05-09 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_productspecification_productvariant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('low_threshold', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='products.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_levels',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(help_text='Positive = inbound, negative = outbound.')),
                ('reason', models.CharField(choices=[('inbound', 'Inbound'), ('order', 'Order Fulfillment'), ('return', 'Return Restock'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='e.g. order_id, PO number', max_length=64)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('stock_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklevel')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['warehouse', 'product'], name='stock_level_warehou_588e6e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('product', 'variant', 'warehouse')},
        ),
    ]
