# Generated by Django 5.2.14 on 2026-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_failure_reason_payment_razorpay_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
