# Generated by Django 5.2.14 on 2026-05-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
