# Generated by Django 5.2.14 on 2026-05-19 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('tag', models.CharField(blank=True, db_index=True, help_text='Free-form tag for segmentation, e.g. "diwali", "dealer".', max_length=80)),
                ('source', models.CharField(default='manual', help_text='How this number was added: manual, csv, customer, dealer.', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sms_contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Message body (max 1000 chars). Variables: {name}.', max_length=1000)),
                ('audience', models.CharField(choices=[('all', 'All contacts'), ('customers', 'Registered customers'), ('dealers', 'Dealers'), ('manual', 'Manual list / CSV import'), ('wishlist', 'Wishlist owners'), ('high_value', 'High-value order customers (>50k)'), ('tag', 'By tag')], default='all', max_length=20)),
                ('audience_tag', models.CharField(blank=True, help_text='Limit to contacts with this tag (when audience=tag).', max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='draft', max_length=10)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='sms_campaigns.campaign')),
            ],
            options={
                'db_table': 'sms_deliveries',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['campaign', 'status'], name='sms_deliver_campaig_1ac15b_idx')],
            },
        ),
    ]
