# Generated by Django 5.2.14 on 2026-05-09 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_cancellation_reason_order_delivered_at_and_more'),
        ('products', '0007_product_brand_product_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'invoice_counters',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('billing_name', models.CharField(max_length=120)),
                ('billing_address_text', models.TextField()),
                ('billing_pincode', models.CharField(blank=True, max_length=10)),
                ('billing_state', models.CharField(blank=True, max_length=80)),
                ('shipping_address_text', models.TextField(blank=True)),
                ('store_name', models.CharField(max_length=120)),
                ('store_legal_name', models.CharField(blank=True, max_length=200)),
                ('store_gstin', models.CharField(blank=True, max_length=15)),
                ('store_address', models.TextField(blank=True)),
                ('store_email', models.EmailField(blank=True, max_length=254)),
                ('store_phone', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=10)),
                ('payment_method', models.CharField(default='razorpay', max_length=20)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True, max_length=500)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.order')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=40)),
                ('variant_label', models.CharField(blank=True, max_length=120)),
                ('hsn_code', models.CharField(blank=True, max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Net of discount, pre-tax.', max_digits=10)),
                ('original_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_subtotal', models.DecimalField(decimal_places=2, help_text='unit_price × quantity (pre-tax).', max_digits=10)),
                ('line_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='subtotal − discount + taxes.', max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='products.productvariant')),
            ],
            options={
                'db_table': 'invoice_items',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payment_status', '-created_at'], name='invoices_payment_1e70a6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer', '-created_at'], name='invoices_custome_38a61a_idx'),
        ),
    ]
