# Generated by Django 5.2.14 on 2026-05-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportticket_guest_email_supportticket_guest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, help_text='Group label, e.g. "Package & delivery".', max_length=80)),
                ('question', models.CharField(help_text='What this Q&A answers, shown as a quick chip.', max_length=240)),
                ('answer', models.TextField(help_text='Bot reply (plain text or simple markdown).')),
                ('triggers', models.JSONField(blank=True, default=list, help_text='Lowercased keywords/phrases the bot matches against.')),
                ('follow_up_prompts', models.JSONField(blank=True, default=list, help_text='Suggested next questions to chip-render after this answer.')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'support_faq_entries',
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
    ]
