# Generated by Django 5.2.13 on 2026-05-06 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_alter_category_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("user", "User Discount"),
                            ("dealer", "Dealer Discount"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage"),
                            ("flat", "Flat Amount (₹)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="15 for 15%, or 2000 for ₹2000 off",
                        max_digits=10,
                    ),
                ),
                (
                    "count_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum units at discounted price. NULL = unlimited.",
                        null=True,
                    ),
                ),
                (
                    "units_sold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Auto-incremented when a discounted unit is ordered.",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_discounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "discounts",
                "indexes": [
                    models.Index(
                        fields=["product", "discount_type"],
                        name="discounts_product_abc4d6_idx",
                    ),
                    models.Index(fields=["active"], name="discounts_active_b7955c_idx"),
                ],
                "unique_together": {("product", "discount_type")},
            },
        ),
    ]
