# Generated by Django 5.2.14 on 2026-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        ('products', '0006_productspecification_productvariant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-min_quantity']},
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='discount',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum cart quantity required for this tier. Use 1 for a flat discount, or build a ladder like 1/2/5/10 with increasing values for volume pricing.'),
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together={('product', 'discount_type', 'min_quantity')},
        ),
    ]
