# Generated by Django 5.2.14 on 2026-05-10 05:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_order_coupon_code_order_coupon_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(choices=[('percent', 'Percent off subtotal'), ('flat', 'Flat amount off subtotal'), ('shipping', 'Free shipping')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Percent (0-100) for type=percent, INR for type=flat. Ignored for shipping.', max_digits=10)),
                ('min_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount', models.DecimalField(decimal_places=2, default=0, help_text='Cap for percent coupons. 0 = no cap.', max_digits=10)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='Total uses across all users. 0 = unlimited.')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('per_user_limit', models.PositiveSmallIntegerField(default=1, help_text='How many times one account can use it. 0 = unlimited.')),
                ('allowed_role', models.CharField(choices=[('user', 'Customer'), ('dealer', 'Dealer'), ('any', 'Any')], default='any', max_length=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='coupons.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupon_redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
