# Generated by Django 5.2.13 on 2026-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="dealer_company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="dealer_gst_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="dealer_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending Approval"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                ],
                help_text="Only relevant when role=dealer",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Customer"),
                    ("dealer", "Dealer"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
