# Generated by Django 5.2.14 on 2026-05-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_dealer_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Blocked users are rejected at login with code=user_blocked.'),
        ),
    ]
