# Generated by Django 5.2.14 on 2026-05-09 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer_pricing', '0001_initial'),
        ('users', '0003_user_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dealer_territory',
            field=models.CharField(blank=True, help_text='Free-text region label, e.g. "South Karnataka".', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dealer_tier',
            field=models.ForeignKey(blank=True, help_text='Pricing tier (standard/premium/platinum). NULL = no tier discount.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='dealer_pricing.dealertier'),
        ),
    ]
