# Generated by Django 5.2.14 on 2026-05-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_useraddress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useraddress',
            new_name='user_addres_user_id_f26943_idx',
            old_name='users_user__is_def_2f8e19_idx',
        ),
        migrations.RenameIndex(
            model_name='useraddress',
            new_name='user_addres_user_id_24a34c_idx',
            old_name='users_user__is_def_1c3b4b_idx',
        ),
    ]
