# Generated by Django 5.2.14 on 2026-05-09 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('block', 'Block'), ('unblock', 'Unblock'), ('approve', 'Approve'), ('reject', 'Reject'), ('refund', 'Refund'), ('cancel', 'Cancel'), ('export', 'Export'), ('other', 'Other')], db_index=True, max_length=20)),
                ('target_type', models.CharField(db_index=True, max_length=80)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='audit_logs_target__9fc8de_idx'), models.Index(fields=['actor', '-created_at'], name='audit_logs_actor_i_3b0e80_idx')],
            },
        ),
    ]
